### ISSUE TITLE
How variable is declared

### ISSUE THREAD

**Issue by TobiasAntiGravity** [robinovitch61/the-leo-zone#1]
Hi robinovitch61

Thank you for the blog post showing how to use jupyter in a docker container and the use of setup_envs.sh. Really the only post explaining this in a good manner as far as I can see!

There is one thing I am not understanding; How is $MYVAR declared. I see it used in the setup_envs.sh, but I cannot see it's declaration anywhere. 

As a side note; I am actually trying to pass a docker secret to the pip install command inside setup_envs.sh to pip from a private repo. Any tips on how to do this?

**Comment by robinovitch61** [comment]
Hi @TobiasAntiGravity , glad you found the post helpful! My quick responses here might be wrong because I haven't dealt with this process in a while, but I'll try to be helpful:

> There is one thing I am not understanding; How is $MYVAR declared. I see it used in the setup_envs.sh, but I cannot see it's declaration anywhere.

I think the line `export MYVAR=$MYVAR` was meant to demonstrate that `$MYVAR` could be any string that you want.

> I am actually trying to pass a docker secret to the pip install command inside setup_envs.sh to pip from a private repo. Any tips on how to do this?

I don't have a specific answer for you but my intuition would be to pass secrets into the docker container at `docker run` time from your local environment. That way your secrets aren't version controlled (they only exist in env vars set locally from non-version-controlled files) and they're accessible to scripts and commands in the docker container via references to environment variables.

**Comment by TobiasAntiGravity** [comment]
Thank you for the quick reply @robinovitch61 !! Appreciated!
